name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: "3.9"

    - uses: actions/checkout@v4

    - name: Install 
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest
